### ISSUE TITLE
renaming for folders/files unavailable

### ISSUE THREAD

**Issue by marcust10** [ignamiranda/plex_debrid_zurg_scripts#3]
unable to rename anime so that plex can get the information properly.
am running your guide but cant manage to find a way for anime sorting/renaming.

**Comment by ignamiranda** [comment]
You cant rename anything but you can change how things are sorted into the category folders in the config (see [wiki](https://github.com/debridmediamanager/zurg-testing/wiki/Config#directory-definitions-and-filters)). Easier file renaming [is being worked on](https://github.com/debridmediamanager/zurg-testing/issues/3).
